package.json, src/data-provider/index.ts, src/global-store.ts, src/kube-api.ts
- Add namespace field in meta object field to handle non-namespace crd resources
- Fix inaccessibility of apiUrl attribute outside global store
- Fix husky script
=> add default namespace to custom crds

src/kube-api.ts
With the live provider, when a k8s watch event fired, the expected behavior is:
1. Update list-watch items according to event type, e.g., ADDED/MODIFIED/DELETED.
2. Set updated items into the global store, via the onResponse callback.
3. Publish the event to the live provider, and notify Apps to re-query from the global store, via the onEvent callback.
So we need to change the order of callbacks to make sure onEvent fires after onResponse.
=> fix callback order

package.json, src/data-provider/index.ts, src/global-store.ts, src/kube-api.ts, src/live-provider/index.ts, yarn.lock
- Bump `@refinedev/core` version to support multi data provider for live provider updates on demand.
- Move `@refinedev/core` to peerDependencies.
- Delete metadata 'managedFields' field when applying yaml.
- Fix dataprovider return types
- Implement K8s resource field level updates
=> Optimizations for dataprovider and kubeapi

.gitignore, __tests__/utils/filter-data.spec.ts, package.json, src/utils/filter-data.ts, yarn.lock
In previous implementations, the in and contains implementations were buggy and could not handle data of array type.
The include function based on lodash and the filtering modeled on prisma implements the in and contains relationship
=> fix: Fix the logic of filters contain/in relation

__tests__/utils/filter-data.spec.ts, src/utils/filter-data.ts
#14 
This fix brings another problem, the in/contains judgment logic is skipped when the value of field value is of type non-array.
=> fix: Fix filter result error when field value is non-array

pnpm-lock.yaml, src/kube-api.ts
Not every K8s resource support the watch API, so before start a ListWatch informer, we should check API verbs.
We already have a cache for ApiResourceList, this patch just extend it so all the KubeApi and KubeSdk instances can share the same cache when they have same basePath.
=> check resource verbs before watch

src/global-store.ts
In k8s, we may have resources like this:
- `/api/v1/pods`
- `/apis/metrics.k8s.io/v1beta1/pods`
Currently, we are using refine's `resource` as the last part of the URL. Since `resource` is one of the most essential concepts in Refine, we'd better let these resources use different names in Refine. Then user can define `k8sResource` in the meta to let our API provider know how to construct an object.
For example:
```ts
{
resource: 'pods',
},
{
resource: 'podMetrics',
meta: {
k8sResource: 'pods'
}
}
```
=> support use meta.k8sResource to override resource name

__tests__/utils/filter-data.spec.ts, src/utils/filter-data.ts
In the current null and nnull judgments, undefined will be erroneously judged to be true.
Adjusted the judgment logic, the judgment rules of null and nnull return true or false according to whether the value is nil.
And complements the logic of recursive judgment.
=> fix: Fix the problem of null judgment error

package.json, src/data-provider/index.ts, src/global-store.ts, src/kube-api.ts, src/utils/filter-data.ts, src/utils/paginate-data.ts
We have exposed the init method in the Global store to enable the ability to reinitialize the Global store externally. However, the init implementation only cleans up the Map, and does not manually close the watch on the k8s resource.
=> feat(global store): implement golbal store destory

__tests__/utils/paginate-data.spec.ts, src/data-provider/index.ts, src/utils/paginate-data.ts
In refine, if pagination mode is client side, the getList method of dataprovider will not be called in setCurrent, because it is realized in the client side, so we should change the original judgment to simulate server mode pagination.
=> fix: fix paginate

src/data-provider/index.ts, src/kube-api.ts
In the previous [MR]( https://github.com/webzard-io/k8s-api-provider/pull/25), we added the forceapply parameter to applyYaml, but if we can distinguish between edit and create, we should call the corresponding method, so we should implement createyaml
=> feat(kube-api): add createyaml

__tests__/utils/transform-http-error.spec.ts, src/data-provider/index.ts, src/utils/transform-http-error.ts
- Instead of returning structured data, an error should be thrown if getOne does not find a match.
- Since refine imposes strict limits on the types of errors, we uniformly return errors of the `HttpError` structure.
=> fix: data api's get one throw error when get empty data and transform http error

.gitignore, src/data-provider/index.ts, src/global-store.ts, src/kube-api.ts
In the original implementation, we didn't manage the timeout for http requests, we set the timeout parameter of ky to false for get data, which means it never times out, and we didn't set the timeout parameter for put/post data, which will result in a default timeout after 1000ms. Since there are requests that don't timeout, it's very likely that we'll trigger the browser's maximum request limit, causing subsequent requests (including non-dataprovider requests) to be pedding. This will have unintended consequences, especially if there are dynamically loaded js files. Therefore, in this PR, we have made the following changes.
- A new `cancelQuery` method has been added, which allows us to cancel the query at the desired point (usually within the lifecycle hook of the corresponding …
=> feat(kube-api): implement cancel query

tsup.config.ts
Don't need to minify the file when building which would lead to can't set the break point in the web dev tool. It should be minified in the other project which uses this lib.
=> chore: remove the minify option

src/kube-api.ts
Not all data in the resource list contains the `apiVersion` and `kind` field.
=> fix: chagne the type Unstructured

src/global-store.ts
在应用启动时，有可能短时间内多次调用global-store的get方法。此时，第一个请求都尚未返回，所以没有缓存，因此就会连续发送多个请求。
这个pr的作用就是缓存get产生的promise。当没有data的缓存，并且请求参数和之前完全相同的话，就返回缓存的promise，而不重复发送请求。
=> cache global store get requests

src/global-store.ts
现在对model调用 restoreItem 时，结果仍然会有relations，没有restore干净。
目前Plugin的proceesItem和restoreItem都是按顺序调用的。目前的顺序是 [relationPlugin, modelPlugin]。结果就是先调用了的relationPlugin的restoreItem，去掉了relation。但是modelPlugin的restoreItem直接返回了rawYaml，导致结果还是有relation。应该反过来，先拿到rawYaml，再去掉relation才正确。
因此，在restoreItem的时候按照plugins的反向顺序调用更加合理一些。
=> call restoreItem func of plugins in reversed order

src/data-provider/index.ts, src/global-store.ts
In the original implementation, we added namespace to the meta attribute of the data-provider in order to implement the k8s api server's filter by namespace feature. However, we ignored the fact that the cache key in the globalstore is the resource name. This will result in an incorrect cache being returned when switching namespaces for the same resource (including switching to all namespaces).The following fixes have been made in this PR：
- Removed the specific namespace parameter for requesting api-server, meaning that  the current resource will be returned fully anyway.
- Filtering the namespace needed within the dataprovider.
=> fix(globalstore): fix resource namespace filter

src/global-store.ts, src/kube-api.ts
In the previous PR https://github.com/webzard-io/k8s-api-provider/pull/34, we added a synchronization lock to `globalStore.get()` to ensure that only one valid http(s) and wbsocket(s) request is sent for the same resource concurrently, but the lock is not sufficiently restrictive: the lock is only added if the request parameters are identical, for the following reason:
- The parameters passed to the dataprovider by the caller will only be used inside the dataprovider and not sent to the k8s api server, the actual request parameters sent to the api server should be determined by the dataprovider.
- In one globalstore instance, we should strictly ensure that only one list watch exists for a resource at a time, otherwise there will be unintended consequences.
This PR also adds the …
=> fix cache quest lock condition

package.json, src/global-store.ts, src/kube-api.ts
把 onEvent 的逻辑整合进 onResponse 中，确保 notify 在 store.set 之后调用，防止由于执行异步函数导致它们的调用顺序不正确。
=> fix: make sure notify is called after store.set

src/kube-api.ts
显式开启k8s的级联删除功能。
k8s文档中说这是默认开启的，但实际上没开启，所以显式配置这个参数，开启级联删除。
https://kubernetes.io/zh-cn/docs/tasks/administer-cluster/use-cascading-deletion/
=> enable cascading deletion

src/kube-api.ts
在原先 ListWatch 的重连逻辑中，存在以下问题：
- 在 websocket 被异常断开后，会触发指数退避重连，在 websocket 重连成功后，需要清理重连状态
- 只处理了 ListWatch 的 wtach 异常重连，未对 list 操作的异常进行重连
当前 PR 包含以下修改：
- 在重连后清理对应的状态字端
- 对重连过程中的 list 操作增加异常重连；对于首次由外部触发（UI）的 ListWatch ，抛出异常，由 UI 手动点击重试进行重连
自测：
=> fix: 🐛 kube api reset retry state after reconnect

src/global-store.ts
In the original implementation, we added the plugin feature to the Global Store to handle the data. However, in some scenarios, we need to load the plugin after initializing the Global Store, and the in-memory cache in the Global Store needs to be rebuilt.
=> feat: 🎸 add loadPlugins to globalstore

src/data-provider/index.ts, src/kube-api.ts
BREAKING CHANGE: 🧨 `Unstructured.metadata` changed to optional
Since the previous type was inaccurate, it was adjusted to match the type of the k8S core resource and CRD.
=> fix: 🐛 fix Unstructured metadata types

src/kube-api.ts
In the past kube api implementations, the fieldManager field was only added when applying yaml. The fieldManager field was omitted when patching and putting json.
If there is no fieldManager, the API server infers a field manager identity from the "User-Agent:" HTTP header (if present).
This will result in the same field being managed by multiple UI client managers, which will result in a failure to remove the field via the client side patch
https://kubernetes.io/docs/reference/using-api/server-side-apply/#managers
=> fix: 🐛 fix missed fieldManager field

.github/workflows/ci-check.yml, .github/workflows/npm-publish-github-packages.yml, package.json, src/kube-api.ts, yarn.lock
Problem: In some cases, the data pushed by WebSocket is returned faster than the POST request, causing the data pushed by watchBySdk to overwrite the data pushed by WebSocket
=> chore: enhance KubeApi watch method to prevent duplicate events

__tests__/utils/extract-path.spec.ts, src/data-provider/index.ts, src/utils/extract-path.ts
In some cases, such as large amounts of data and frequent CR updates, some fields are used to store data using the `Array` data structure in order to compress the data size.
In this case, we expect to use the sorting/paging capabilities provided by the dataprovider, so we added the extract path configuration
=> feat: 🎸 add extract path util for data provider

__tests__/k8sClient.ts, __tests__/utils/extract-path.spec.ts, __tests__/utils/filter-data.spec.ts, __tests__/utils/paginate-data.spec.ts, __tests__/utils/sort-data.spec.ts, jest.config.js, package.json, src/global-store.ts, src/kube-api.ts, src/utils/extract-path.ts, src/utils/filter-data.ts, src/utils/sort-data.ts, tsconfig.json, yarn.lock
add destroy lock
Vulnerability in destroy: After calling destroy, registration of subsequent callbacks should be disabled.
BTW: cause of `ky` package only builds ESM bundle, jest didn't work with it.
=> fix: 🐛 fix destroy lock

src/global-store.ts
1. Cause of requestsCache didn't  lock `listWatch onResponse` callback, In some cases, multiple connections may have been established and the older connections are not managed by the global store.
2. In [previous fix](https://github.com/webzard-io/k8s-api-provider/pull/53) `_isDestroyed` has too great a reach, The flag should only affect the get method
Before
We can see that two connections were established when the same resource was initialized, and that the connection established first was taken out of the management
After
BTW, there is an another case left: if the request onResponse callback is timeout and didn't trigger error, the cache request lock will not be removed
=> fix: 🐛 fix destroy and cacheRequest lock

src/global-store.ts
修改和删除有可能有竞态关系。当短时间内收到修改和删除事件时，若修改的异步处理`processData`较慢，可能导致UI状态不一致。结果导致先发生的修改事件，在删除事件之后执行，导致已删除的资源仍然存在。
修复方法是，收到修改事件后，在异步操作完成后，更新store之前，检查资源是否存在，如果已经不存在，就不再添加。
=> fix: fix globalStore modify event race condition
